In [1]:
import pandas as pd

In [31]:

#Function assigning a non standard level-floor to other category
def assign_level(item):
    approved_lst = ["Ισόγειο", "1ος", "2ος", "3ος", "4ος", "5ος", "6ος", "7ος", "8ος", "Υπερυψωμένο", "Ημιυπόγειο", "Ημιώροφος" ]
    try:
        if item not in approved_lst:
            item = "'Αλλο"
            return item
        else:
            return item
    except:
        pass

In [43]:
#Function assigning more than 10 bedrooms to category 10
def assign_bedroom(item):
    try:
        if item >9:
            item = 10
            return item
        else:
            return item
    except:
        pass

In [46]:
#Function assigning more than 10 bedrooms to category 10
def assign_bathroom(item):
    try:
        if item >5:
            item = 6
            return item
        else:
            return item
    except:
        pass

In [61]:
df=pd.read_csv("../data/greece_listings.csv")
df.shape

(20000, 25)

In [62]:
pd.set_option('display.max_columns', None)
df.head()

,location_name,location_region,res_date,res_type,res_address,res_price,res_price_sqr,res_sqr,construction_year,levels,bedrooms,bathrooms,deleted,deleted_at,status,energyclass,auto_heating,solar,cooling,safe_door,gas,fireplace,furniture,student,parking
0,Παλαιό Φάληρο,Αττική,2021-06-18,Διαμέρισμα,"Παλαιό Φάληρο,Γήπεδα",89000,1618.0,55.0,1973.0,Υπερυψωμένο,1.0,1.0,1,2022-04-05 00:00:00,Ανακαινισμένο,Δ,1,0,1,1,0,0,0,0,NaN
1,Αχαρνές,Αττική,2022-03-30,Μεζονέτα,"Αχαρνές,Λαθέα",150000,1531.0,98.0,2010.0,4ος,2.0,1.0,1,2022-05-19 00:00:00,Νεόδμητο,Γ,0,0,0,0,0,1,0,0,Κλειστό parking
2,Παγκράτι,Αττική,2022-02-25,Διαμέρισμα,"Αθήνα,Παγκράτι",400000,3175.0,126.0,1990.0,3ος,3.0,1.0,1,2022-06-10 00:00:00,Άριστη,Δ,1,0,1,1,0,1,0,0,NaN
3,Αθήνα,Αττική,2022-03-21,Διαμέρισμα,"Αθήνα,Άγιος Παντελεήμονας",80000,941.0,85.0,1957.0,5ος,2.0,1.0,1,2022-03-23 00:00:00,Καλή,Ζ,1,0,0,1,0,0,0,1,NaN
4,Ίλιον,Αττική,2022-01-11,Διαμέρισμα,"Αθήνα,Άγιος Ελευθέριος",100000,2083.0,48.0,1996.0,1ος,1.0,1.0,1,2022-04-14 00:00:00,Καλή,Δ,1,0,0,1,0,0,0,0,NaN

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   location_name      20000 non-null  str
 1   location_region    20000 non-null  str
 2   res_date           20000 non-null  str
 3   res_type           20000 non-null  str
 4   res_address        20000 non-null  str
 5   res_price          20000 non-null  int64
 6   res_price_sqr      19998 non-null  float64
 7   res_sqr            19999 non-null  float64
 8   construction_year  19214 non-null  float64
 9   levels             19992 non-null  str
 10  bedrooms           18935 non-null  float64
 11  bathrooms          18214 non-null  float64
 12  deleted            20000 non-null  int64
 13  deleted_at         16885 non-null  str
 14  status             18195 non-null  str
 15  energyclass        18186 non-null  str
 16  auto_heating       20000 non-null  int64
 17  solar              20000 non-null  int64
 18  cooling            20000 non-null  int64
 19  safe_door          20000 non-null  int64
 20  gas                20000 non-null  int64
 21  fireplace          20000 non-null  int64
 22  furniture          20000 non-null  int64
 23  student            20000 non-null  int64
 24  parking            3315 non-null   str
dtypes: float64(5), int64(10), str(10)
memory usage: 3.8 MB

In [65]:
#Flag properties that have (1) or not (0) any type of parking
df["parking_flag"] = df["parking"].notnull()
df["parking_flag"] = df["parking_flag"].replace(True, 1)
df["parking_flag"] = df["parking_flag"].replace(False, 0)
df.shape

(20000, 26)

In [67]:
df = df.loc[(df["location_region"] == "Αττική")]
df.shape

(18813, 26)

In [37]:
df["levels"].unique()

<StringArray>
[                                   'Υπερυψωμένο',
                                            '4ος',
                                            '3ος',
                                            '5ος',
                                            '1ος',
                                     'Ημιυπόγειο',
                        'Υπόγειο,Ισόγειο,1ος,2ος',
                                            '2ος',
                                        'Ισόγειο',
                            'Ισόγειο,1ος,2ος,3ος',
 ...
                 'Υπόγειο,Ημιυπόγειο,Ισόγειο,1ος',
                        '3ος,4ος,5ος,6ος,7ος,8ος',
                        'Υπόγειο,Υπερυψωμένο,1ος',
                           'Ημιυπόγειο,Ημιώροφος',
             'Ημιυπόγειο,Ισόγειο,1ος,2ος,3ος,4ος',
           'Υπόγειο,Ημιυπόγειο,Ισόγειο,Ημιώροφος',
        'Υπόγειο,Ισόγειο,Υπερυψωμένο,1ος,2ος,3ος',
 'Υπόγειο,Ημιυπόγειο,Ισόγειο,1ος,2ος,3ος,4ος,5ος',
      'Υπόγειο,Ισόγειο,Ημιώροφος,1ος,2ος,3ος,4ος',
                '1ος,2ος,3ος,4ος,5ος,6ος,7ος,8ος']
Length: 108, dtype: str

In [38]:
df.groupby("levels").count().reset_index().sort_values("location_region", ascending=False).head(20)

,levels,location_name,location_region,res_date,res_type,res_address,res_price,res_price_sqr,res_sqr,construction_year,bedrooms,bathrooms,deleted,deleted_at,status,energyclass,auto_heating,solar,cooling,safe_door,gas,fireplace,furniture,student,parking,parking_flag
58,Ισόγειο,4323,4323,4323,4323,4323,4323,4323,4323,4146,3837,3705,4323,3690,3827,3738,4323,4323,4323,4323,4323,4323,4323,4323,694,4323
0,1ος,3298,3298,3298,3298,3298,3298,3298,3298,3200,3196,3075,3298,2924,2989,3032,3298,3298,3298,3298,3298,3298,3298,3298,522,3298
8,2ος,2434,2434,2434,2434,2434,2434,2434,2434,2350,2383,2279,2434,2196,2224,2231,2434,2434,2434,2434,2434,2434,2434,2434,386,2434
12,3ος,2089,2089,2089,2089,2089,2089,2089,2089,2019,2041,1967,2089,1858,1933,1924,2089,2089,2089,2089,2089,2089,2089,2089,357,2089
16,4ος,1508,1508,1508,1508,1508,1508,1507,1508,1461,1467,1421,1508,1338,1389,1405,1508,1508,1508,1508,1508,1508,1508,1508,249,1508
21,5ος,1126,1126,1126,1126,1126,1126,1126,1126,1074,1098,1073,1126,1019,1042,1060,1126,1126,1126,1126,1126,1126,1126,1126,176,1126
59,"Ισόγειο,1ος",482,482,482,482,482,482,482,482,442,447,412,482,384,447,445,482,482,482,482,482,482,482,482,76,482
25,6ος,443,443,443,443,443,443,443,443,433,434,417,443,404,416,419,443,443,443,443,443,443,443,443,99,443
60,"Ισόγειο,1ος,2ος",405,405,405,405,405,405,405,405,371,371,349,405,322,390,378,405,405,405,405,405,405,405,405,50,405
77,Υπερυψωμένο,385,385,385,385,385,385,385,385,363,372,353,385,322,300,314,385,385,385,385,385,385,385,385,14,385
31,Ημιυπόγειο,351,351,351,351,351,351,351,351,334,309,311,351,315,307,321,351,351,351,351,351,351,351,351,2,351
28,7ος,205,205,205,205,205,205,205,205,202,201,194,205,182,191,194,205,205,205,205,205,205,205,205,46,205
54,Ημιώροφος,191,191,191,191,191,191,191,191,180,183,180,191,176,186,184,191,191,191,191,191,191,191,191,5,191
61,"Ισόγειο,1ος,2ος,3ος",155,155,155,155,155,155,155,155,150,132,127,155,128,152,149,155,155,155,155,155,155,155,155,11,155
17,"4ος,5ος",127,127,127,127,127,127,127,127,114,123,117,127,121,125,123,127,127,127,127,127,127,127,127,34,127
22,"5ος,6ος",122,122,122,122,122,122,122,122,120,121,115,122,109,120,120,122,122,122,122,122,122,122,122,23,122
13,"3ος,4ος",113,113,113,113,113,113,113,113,96,109,102,113,102,108,109,113,113,113,113,113,113,113,113,23,113
82,Υπόγειο,112,112,112,112,112,112,112,112,109,98,97,112,90,104,103,112,112,112,112,112,112,112,112,16,112
1,"1ος,2ος",101,101,101,101,101,101,101,101,96,95,93,101,87,91,91,101,101,101,101,101,101,101,101,24,101
9,"2ος,3ος",97,97,97,97,97,97,97,97,89,96,89,97,89,92,95,97,97,97,97,97,97,97,97,22,97

In [39]:
df["levels"] = list(map(assign_level, df['levels']))
df["levels"].unique()

<StringArray>
['Υπερυψωμένο',         '4ος',         '3ος',         '5ος',         '1ος',
  'Ημιυπόγειο',       ''Αλλο',         '2ος',     'Ισόγειο',         '6ος',
   'Ημιώροφος',         '8ος',         '7ος']
Length: 13, dtype: str

In [40]:
df.groupby("levels").count()

,location_name,location_region,res_date,res_type,res_address,res_price,res_price_sqr,res_sqr,construction_year,bedrooms,bathrooms,deleted,deleted_at,status,energyclass,auto_heating,solar,cooling,safe_door,gas,fireplace,furniture,student,parking,parking_flag
levels,,,,,,,,,,,,,,,,,,,,,,,,,
'Αλλο,2368,2368,2368,2368,2368,2368,2367,2367,2185,2156,2003,2368,1951,2213,2157,2368,2368,2368,2368,2368,2368,2368,2368,538,2368
1ος,3298,3298,3298,3298,3298,3298,3298,3298,3200,3196,3075,3298,2924,2989,3032,3298,3298,3298,3298,3298,3298,3298,3298,522,3298
2ος,2434,2434,2434,2434,2434,2434,2434,2434,2350,2383,2279,2434,2196,2224,2231,2434,2434,2434,2434,2434,2434,2434,2434,386,2434
3ος,2089,2089,2089,2089,2089,2089,2089,2089,2019,2041,1967,2089,1858,1933,1924,2089,2089,2089,2089,2089,2089,2089,2089,357,2089
4ος,1508,1508,1508,1508,1508,1508,1507,1508,1461,1467,1421,1508,1338,1389,1405,1508,1508,1508,1508,1508,1508,1508,1508,249,1508
5ος,1126,1126,1126,1126,1126,1126,1126,1126,1074,1098,1073,1126,1019,1042,1060,1126,1126,1126,1126,1126,1126,1126,1126,176,1126
6ος,443,443,443,443,443,443,443,443,433,434,417,443,404,416,419,443,443,443,443,443,443,443,443,99,443
7ος,205,205,205,205,205,205,205,205,202,201,194,205,182,191,194,205,205,205,205,205,205,205,205,46,205
8ος,92,92,92,92,92,92,92,92,88,90,84,92,81,83,84,92,92,92,92,92,92,92,92,16,92
Ημιυπόγειο,351,351,351,351,351,351,351,351,334,309,311,351,315,307,321,351,351,351,351,351,351,351,351,2,351
Ημιώροφος,191,191,191,191,191,191,191,191,180,183,180,191,176,186,184,191,191,191,191,191,191,191,191,5,191
Ισόγειο,4323,4323,4323,4323,4323,4323,4323,4323,4146,3837,3705,4323,3690,3827,3738,4323,4323,4323,4323,4323,4323,4323,4323,694,4323
Υπερυψωμένο,385,385,385,385,385,385,385,385,363,372,353,385,322,300,314,385,385,385,385,385,385,385,385,14,385

In [42]:
df.groupby("bedrooms").count()

,location_name,location_region,res_date,res_type,res_address,res_price,res_price_sqr,res_sqr,construction_year,levels,bathrooms,deleted,deleted_at,status,energyclass,auto_heating,solar,cooling,safe_door,gas,fireplace,furniture,student,parking,parking_flag
bedrooms,,,,,,,,,,,,,,,,,,,,,,,,,
1.0,3555,3555,3555,3555,3555,3555,3555,3555,3445,3555,3340,3555,3176,3218,3240,3555,3555,3555,3555,3555,3555,3555,3555,194,3555
2.0,6444,6444,6444,6444,6444,6444,6444,6444,6233,6444,6117,6444,5707,5853,5914,6444,6444,6444,6444,6444,6444,6444,6444,882,6444
3.0,5012,5012,5012,5012,5012,5012,5011,5012,4825,5012,4798,5012,4435,4652,4634,5012,5012,5012,5012,5012,5012,5012,5012,1178,5012
4.0,1504,1504,1504,1504,1504,1504,1504,1504,1450,1504,1419,1504,1264,1344,1315,1504,1504,1504,1504,1504,1504,1504,1504,442,1504
5.0,553,553,553,553,553,553,553,553,530,553,521,553,434,486,478,553,553,553,553,553,553,553,553,165,553
6.0,293,293,293,293,293,293,293,293,288,293,262,293,235,267,248,293,293,293,293,293,293,293,293,86,293
7.0,135,135,135,135,135,135,135,135,132,135,124,135,109,114,102,135,135,135,135,135,135,135,135,30,135
8.0,85,85,85,85,85,85,85,85,79,85,73,85,64,72,66,85,85,85,85,85,85,85,85,12,85
9.0,42,42,42,42,42,42,42,42,41,42,40,42,34,36,32,42,42,42,42,42,42,42,42,4,42
10.0,49,49,49,49,49,49,49,49,49,49,45,49,37,43,40,49,49,49,49,49,49,49,49,10,49
11.0,10,10,10,10,10,10,10,10,9,10,9,10,8,9,8,10,10,10,10,10,10,10,10,6,10
12.0,24,24,24,24,24,24,24,24,24,24,22,24,22,20,21,24,24,24,24,24,24,24,24,6,24
13.0,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,4,4,4,4,4,4,4,4,0,4
14.0,11,11,11,11,11,11,11,11,10,11,10,11,10,11,11,11,11,11,11,11,11,11,11,5,11
15.0,7,7,7,7,7,7,7,7,6,7,4,7,5,4,4,7,7,7,7,7,7,7,7,1,7
16.0,10,10,10,10,10,10,10,10,10,10,10,10,10,9,9,10,10,10,10,10,10,10,10,1,10
17.0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3
18.0,6,6,6,6,6,6,6,6,6,6,4,6,5,5,4,6,6,6,6,6,6,6,6,2,6
19.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1
20.0,7,7,7,7,7,7,7,7,7,7,7,7,6,7,5,7,7,7,7,7,7,7,7,2,7
22.0,3,3,3,3,3,3,3,3,3,3,3,3,1,3,2,3,3,3,3,3,3,3,3,1,3
24.0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1
26.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1
27.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1
30.0,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,0,2
33.0,1,1,1,1,1,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1
39.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
40.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1
51.0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1

In [44]:
df["bedrooms"] = list(map(assign_bedroom, df['bedrooms']))
df["bedrooms"].unique()

array([ 1.,  2.,  3., nan,  6.,  4.,  5.,  7.,  9.,  8., 10.])

In [45]:
df.groupby("bathrooms").count()

,location_name,location_region,res_date,res_type,res_address,res_price,res_price_sqr,res_sqr,construction_year,levels,bedrooms,deleted,deleted_at,status,energyclass,auto_heating,solar,cooling,safe_door,gas,fireplace,furniture,student,parking,parking_flag
bathrooms,,,,,,,,,,,,,,,,,,,,,,,,,
1.0,12435,12435,12435,12435,12435,12435,12434,12435,12097,12435,12236,12435,11088,11357,11473,12435,12435,12435,12435,12435,12435,12435,12435,1523,12435
2.0,2778,2778,2778,2778,2778,2778,2778,2778,2652,2778,2759,2778,2399,2521,2466,2778,2778,2778,2778,2778,2778,2778,2778,769,2778
3.0,1025,1025,1025,1025,1025,1025,1025,1025,965,1025,1017,1025,835,930,892,1025,1025,1025,1025,1025,1025,1025,1025,325,1025
4.0,430,430,430,430,430,430,430,430,420,430,426,430,342,382,361,430,430,430,430,430,430,430,430,136,430
5.0,194,194,194,194,194,194,194,194,186,194,191,194,158,176,169,194,194,194,194,194,194,194,194,67,194
6.0,81,81,81,81,81,81,81,81,80,81,78,81,70,75,70,81,81,81,81,81,81,81,81,21,81
7.0,38,38,38,38,38,38,38,38,35,38,37,38,30,35,31,38,38,38,38,38,38,38,38,17,38
8.0,26,26,26,26,26,26,26,26,24,26,25,26,17,23,20,26,26,26,26,26,26,26,26,8,26
9.0,11,11,11,11,11,11,11,11,11,11,10,11,8,9,10,11,11,11,11,11,11,11,11,2,11
10.0,13,13,13,13,13,13,13,13,13,13,12,13,11,12,10,13,13,13,13,13,13,13,13,3,13
11.0,3,3,3,3,3,3,3,3,3,3,3,3,3,2,1,3,3,3,3,3,3,3,3,1,3
12.0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2
13.0,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,4,4,4,4,4,4,4,4,2,4
14.0,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,3,3,3,3,3,3,3,2,3
15.0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3
16.0,5,5,5,5,5,5,5,5,5,5,4,5,5,4,3,5,5,5,5,5,5,5,5,1,5
17.0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3
18.0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,0,2
20.0,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,0,3
22.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
24.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1
26.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [47]:
df["bathrooms"] = list(map(assign_bathroom, df['bathrooms']))
df["bathrooms"].unique()

array([ 1.,  2., nan,  3.,  4.,  5.,  6.])

In [48]:
df["status"].unique()

<StringArray>
[     'Ανακαινισμένο',           'Νεόδμητο',             'Άριστη',
               'Καλή',                  nan, 'Χρήζει ανακαίνισης',
     'Άλλη κατάσταση',           'Ημιτελές',      'Υπο κατασκευή']
Length: 9, dtype: str

In [50]:
df["energyclass"].unique()

<StringArray>
[           'Δ',            'Γ',            'Ζ',     'Εκρεμμεί',
            'Ε',            nan, 'Μη αποδοτικό',           'Β+',
            'Η',           'Α+',            'Α',            'Β',
   'Εξαιρείται']
Length: 13, dtype: str

In [51]:
df["auto_heating"].unique()

array([1, 0])

In [52]:
df["solar"].unique()

array([0, 1])

In [53]:
df["gas"].unique()

array([0, 1])

In [57]:
df["res_date"] = pd.to_datetime(df['res_date'])
df["deleted_at"] = pd.to_datetime(df['deleted_at'])
df.head()

,location_name,location_region,res_date,res_type,res_address,res_price,res_price_sqr,res_sqr,construction_year,levels,bedrooms,bathrooms,deleted,deleted_at,status,energyclass,auto_heating,solar,cooling,safe_door,gas,fireplace,furniture,student,parking,parking_flag
0,Παλαιό Φάληρο,Αττική,2021-06-18,Διαμέρισμα,"Παλαιό Φάληρο,Γήπεδα",89000,1618.0,55.0,1973.0,Υπερυψωμένο,1.0,1.0,1,2022-04-05,Ανακαινισμένο,Δ,1,0,1,1,0,0,0,0,NaN,0
1,Αχαρνές,Αττική,2022-03-30,Μεζονέτα,"Αχαρνές,Λαθέα",150000,1531.0,98.0,2010.0,4ος,2.0,1.0,1,2022-05-19,Νεόδμητο,Γ,0,0,0,0,0,1,0,0,Κλειστό parking,1
2,Παγκράτι,Αττική,2022-02-25,Διαμέρισμα,"Αθήνα,Παγκράτι",400000,3175.0,126.0,1990.0,3ος,3.0,1.0,1,2022-06-10,Άριστη,Δ,1,0,1,1,0,1,0,0,NaN,0
3,Αθήνα,Αττική,2022-03-21,Διαμέρισμα,"Αθήνα,Άγιος Παντελεήμονας",80000,941.0,85.0,1957.0,5ος,2.0,1.0,1,2022-03-23,Καλή,Ζ,1,0,0,1,0,0,0,1,NaN,0
4,Ίλιον,Αττική,2022-01-11,Διαμέρισμα,"Αθήνα,Άγιος Ελευθέριος",100000,2083.0,48.0,1996.0,1ος,1.0,1.0,1,2022-04-14,Καλή,Δ,1,0,0,1,0,0,0,0,NaN,0

In [60]:
df["days_up"] = df["deleted_at"] - df["res_date"]
df.head()
df.shape

(18813, 27)

In [59]:
df.to_csv("../cleaning/clean_greece_listings.csv")